USE AmazonReviewAnalytics;
GO

-- Create the main view using OPENROWSET
IF EXISTS (SELECT * FROM sys.views WHERE name = 'v_gold_reviews_complete')
BEGIN
    DROP VIEW v_gold_reviews_complete;
END
GO

CREATE VIEW v_gold_reviews_complete AS
SELECT 
    review_id,
    reviewer_id,
    review_text,
    summary,
    helpful_votes,
    total_votes,
    is_verified,
    unix_ts,
    review_time,
    review_year,
    review_month,
    review_quarter,
    review_length,
    summary_length,
    word_count,
    helpfulness_ratio,
    rating_category,
    period,
    has_text,
    has_rating,
    is_complete,
    rating,
    asin_unified,
    product_title,
    main_category,
    product_price,
    brand,
    store,
    match_type,
    vader_compound,
    vader_positive,
    vader_neutral,
    vader_negative,
    textblob_polarity,
    textblob_subjectivity,
    rule_based_score,
    ensemble_score,
    final_sentiment,
    sentiment_confidence,
    has_exclamation,
    has_caps,
    question_count,
    exclamation_count,
    avg_word_length,
    reading_ease,
    complexity_score,
    sentiment_intensity,
    rating_sentiment_alignment,
    review_quality_score,
    sentiment_volatility,
    text_emotionality,
    review_completeness,
    processed_timestamp,
    processing_batch_id,
    sentiment_model_version,
    analysis_date,
    review_date,
    data_source,
    sentiment_analysis_method,
    processing_environment,
    processing_cluster,
    is_weekend,
    season,
    is_holiday_season,
    day_of_week,
    day_of_month,
    week_of_year,
    is_month_start,
    is_month_end,
    has_review_text,
    has_sentiment,
    is_complete_record
FROM OPENROWSET(
    BULK 'https://amzdata20376.dfs.core.windows.net/datalake/gold/reviews_sentiment_complete/',
    FORMAT = 'DELTA'
) WITH (
    review_id VARCHAR(100),
    reviewer_id VARCHAR(100),
    review_text VARCHAR(MAX),
    summary VARCHAR(MAX),
    helpful_votes INT,
    total_votes INT,
    is_verified BIT,
    unix_ts BIGINT,
    review_time VARCHAR(100),
    review_year INT,
    review_month INT,
    review_quarter INT,
    review_length INT,
    summary_length INT,
    word_count INT,
    helpfulness_ratio FLOAT,
    rating_category VARCHAR(50),
    period VARCHAR(50),
    has_text BIT,
    has_rating BIT,
    is_complete BIT,
    rating FLOAT,
    asin_unified VARCHAR(50),
    product_title VARCHAR(MAX),
    main_category VARCHAR(200),
    product_price FLOAT,
    brand VARCHAR(MAX),
    store VARCHAR(200),
    match_type VARCHAR(100),
    vader_compound FLOAT,
    vader_positive FLOAT,
    vader_neutral FLOAT,
    vader_negative FLOAT,
    textblob_polarity FLOAT,
    textblob_subjectivity FLOAT,
    rule_based_score FLOAT,
    ensemble_score FLOAT,
    final_sentiment VARCHAR(50),
    sentiment_confidence FLOAT,
    has_exclamation BIT,
    has_caps BIT,
    question_count INT,
    exclamation_count INT,
    avg_word_length FLOAT,
    reading_ease FLOAT,
    complexity_score FLOAT,
    sentiment_intensity VARCHAR(50),
    rating_sentiment_alignment VARCHAR(50),
    review_quality_score FLOAT,
    sentiment_volatility FLOAT,
    text_emotionality FLOAT,
    review_completeness FLOAT,
    processed_timestamp DATETIME2,
    processing_batch_id VARCHAR(100),
    sentiment_model_version VARCHAR(100),
    analysis_date DATE,
    review_date DATE,
    data_source VARCHAR(100),
    sentiment_analysis_method VARCHAR(100),
    processing_environment VARCHAR(100),
    processing_cluster VARCHAR(100),
    is_weekend BIT,
    season VARCHAR(50),
    is_holiday_season BIT,
    day_of_week INT,
    day_of_month INT,
    week_of_year INT,
    is_month_start BIT,
    is_month_end BIT,
    has_review_text BIT,
    has_sentiment BIT,
    is_complete_record BIT
) AS [result];
GO

-- Test the main view
SELECT TOP 5
    review_id,
    asin_unified,
    rating,
    review_year,
    final_sentiment,
    LEFT(product_title, 100) as product_title_short
FROM v_gold_reviews_complete
WHERE review_year IS NOT NULL
ORDER BY review_year DESC;